name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.4'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          cache: 'false'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'true'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==2.1.*'
          py7zrversion: '==0.19.*'
          extra: '--external 7z'
          
      - name: Check inv.
        run: |
          dir
          cd /home/runner/work/some_github_actions/some_github_actions/example//Qt
          dir

      - name: Clone from bitbucket
        run: |
          git clone https://Leartiz@bitbucket.org/Leartiz/plantuml_to_structs_converter.git
          cd plantuml_to_structs_converter/converter/test
          /home/runner/work/some_github_actions/some_github_actions/example//Qt/qmake
